apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: timestamp
spec:
  partitions: 3
---

apiVersion: projectriff.io/v1
kind: Function
metadata:
  name: timestamp
spec:
  protocol: stdio
  input: timestamp
  container:
    image: projectriff/timestamp:0.0.1