apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: echo-node
---

apiVersion: projectriff.io/v1
kind: Function
metadata:
  name: echo-node
spec:
  protocol: http
  input: echo-node
  container:
    image: projectriff/echo-node:0.0.1